// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD9Fa167fpxoRKB82b2rRWN6EFdciZPaI',
    appId: '1:77213927222:web:d58053171714c794155597',
    messagingSenderId: '77213927222',
    projectId: 'new-flutter-app-fcc31',
    authDomain: 'new-flutter-app-fcc31.firebaseapp.com',
    storageBucket: 'new-flutter-app-fcc31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyYnW7On4ZJY1ZLfxiN26ob9XAqobSzaU',
    appId: '1:77213927222:android:535cc956d6ac4428155597',
    messagingSenderId: '77213927222',
    projectId: 'new-flutter-app-fcc31',
    storageBucket: 'new-flutter-app-fcc31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlJemPigOCdErKV8EX7wOBT7agfAGAU5o',
    appId: '1:77213927222:ios:c6c67ab9c4cc4eca155597',
    messagingSenderId: '77213927222',
    projectId: 'new-flutter-app-fcc31',
    storageBucket: 'new-flutter-app-fcc31.appspot.com',
    iosClientId: '77213927222-272jus1r3ce5uvhr49unhlrgrqqhhvdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlJemPigOCdErKV8EX7wOBT7agfAGAU5o',
    appId: '1:77213927222:ios:c6c67ab9c4cc4eca155597',
    messagingSenderId: '77213927222',
    projectId: 'new-flutter-app-fcc31',
    storageBucket: 'new-flutter-app-fcc31.appspot.com',
    iosClientId: '77213927222-272jus1r3ce5uvhr49unhlrgrqqhhvdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSetup',
  );
}
